services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${QBITTORRENT_WEBUI_PORT}
    volumes:
      - /srv/qbittorrent/config:/config
      - /srv/media/downloads:/downloads
    ports:
      - "${QBITTORRENT_WEBUI_PORT}:${QBITTORRENT_WEBUI_PORT}"
      - "6881:6881"
      - "6881:6881/udp"
    networks:
      - media-network

networks:
  media-network:
    name: media-network
    external: true
