services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /srv/sonarr/config:/config
      - /srv/media/tvshows:/tv
      - /srv/media/downloads:/downloads
    ports:
      - "${SONARR_PORT}:8989"
    networks:
      - media-network

networks:
  media-network:
    name: media-network
    external: true
