services:
  electrs:
    image: mempool/electrs
    container_name: electrs
    restart: unless-stopped
    depends_on:
      - bitcoin-core
    environment:
      - DAEMON_RPC_ADDR=bitcoin-core:${BITCOIN_RPC_PORT}
      - DAEMON_P2P_ADDR=bitcoin-core:${BITCOIN_P2P_PORT}
      - DAEMON_RPC_USER=${BITCOIN_RPC_USER}
      - DAEMON_RPC_PASS=${BITCOIN_RPC_PASSWORD}
      - ELECTRS_DB_DIR=/data
      - ELECTRS_NETWORK=bitcoin
      - ELECTRS_LOG_LEVEL=info
    volumes:
      - /srv/electrs/data:/data
    ports:
      - "${ELECTRS_PORT}:50001"
    networks:
      - crypto-network

networks:
  crypto-network:
    name: crypto-network
    external: true
