services:
  bitcoin-core:
    image: bitcoin/bitcoin:latest
    container_name: bitcoin-core
    restart: unless-stopped
    command:
      - -printtoconsole
      - -txindex=1
      - -server=1
      - -rest
      - -rpcbind=0.0.0.0
      - -rpcallowip=10.0.0.0/8
      - -rpcallowip=172.16.0.0/12
      - -rpcallowip=192.168.0.0/16
      - -rpcuser=${BITCOIN_RPC_USER}
      - -rpcpassword=${BITCOIN_RPC_PASSWORD}
      - -zmqpubrawblock=tcp://0.0.0.0:${BITCOIN_ZMQ_RAWBLOCK_PORT}
      - -zmqpubrawtx=tcp://0.0.0.0:${BITCOIN_ZMQ_RAWTX_PORT}
      - -zmqpubhashblock=tcp://0.0.0.0:${BITCOIN_ZMQ_HASHBLOCK_PORT}
      - -zmqpubsequence=tcp://0.0.0.0:${BITCOIN_ZMQ_SEQUENCE_PORT}
      - -dbcache=${BITCOIN_DBCACHE}
      - -maxmempool=${BITCOIN_MAXMEMPOOL}
    volumes:
      - /srv/bitcoin/data:/home/bitcoin/.bitcoin
    ports:
      - "${BITCOIN_RPC_PORT}:8332"
      - "${BITCOIN_P2P_PORT}:8333"
      - "${BITCOIN_ZMQ_RAWBLOCK_PORT}:${BITCOIN_ZMQ_RAWBLOCK_PORT}"
      - "${BITCOIN_ZMQ_RAWTX_PORT}:${BITCOIN_ZMQ_RAWTX_PORT}"
      - "${BITCOIN_ZMQ_HASHBLOCK_PORT}:${BITCOIN_ZMQ_HASHBLOCK_PORT}"
      - "${BITCOIN_ZMQ_SEQUENCE_PORT}:${BITCOIN_ZMQ_SEQUENCE_PORT}"
    networks:
      - crypto-network
    mem_limit: ${BITCOIN_MEMORY_LIMIT}
    healthcheck:
      test: ["CMD-SHELL", "bitcoin-cli -rpcconnect=127.0.0.1 -rpcport=8332 -rpcuser=${BITCOIN_RPC_USER} -rpcpassword=${BITCOIN_RPC_PASSWORD} getblockchaininfo >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  electrs:
    image: mempool/electrs
    container_name: electrs
    restart: unless-stopped
    depends_on:
      bitcoin-core:
        condition: service_healthy
    environment:
      - DAEMON_RPC_ADDR=bitcoin-core:${BITCOIN_RPC_PORT}
      - DAEMON_P2P_ADDR=bitcoin-core:${BITCOIN_P2P_PORT}
      - DAEMON_RPC_USER=${BITCOIN_RPC_USER}
      - DAEMON_RPC_PASS=${BITCOIN_RPC_PASSWORD}
      - ELECTRS_DB_DIR=/data
      - ELECTRS_NETWORK=bitcoin
      - ELECTRS_LOG_LEVEL=info
    volumes:
      - /srv/electrs/data:/data
    ports:
      - "${ELECTRS_PORT}:50001"
    networks:
      - crypto-network

networks:
  crypto-network:
    name: crypto-network
    external: true
